apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: readonly-rolebinding-cluster
subjects:
- kind: User
  name: read-only
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: readonly-role-cluster
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: readonly-rolebinding-default
  namespace: default
subjects:
- kind: User
  name: read-only
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: readonly-role-default
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: readonly-rolebinding-wordpress
  namespace: wordpress
subjects:
- kind: User
  name: read-only
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: readonly-role-wordpress
  apiGroup: rbac.authorization.k8s.io
