kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: readonly-clusterrole
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["", "extensions", "apps"]
  resources: ["namespaces"]
  verbs: ["get"]
  resourceNames: ["wordpress", "nginx"]
