apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: readonly-role-cluster
rules:  
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: readonly-role-default
  namespace: default
rules:
- apiGroups: ["*"]
  resources: ["pods", "services", "deployments"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: readonly-role-wordpress
  namespace: wordpress
rules:
- apiGroups: ["*"]
  resources: ["pods", "services", "deployments"]
  verbs: ["get", "list", "watch"]
